#!/bin/bash

# shellcheck disable=SC2164
cd arm-dependencies
git pull origin main
cd ..

if ! [[ -z $(git diff arm-dependencies) ]]; then 
	git add arm-dependencies
	git commit -m "updated dependencies"
fi
