#!/usr/bin/env bash
# Regenerate frontend/src/lib/types/api.gen.ts from the FastAPI app's
# OpenAPI schema. Runs the Python dump step then the Node generator.
# Pre-commit hook and CI codegen-check both invoke this script.
set -euo pipefail

# Resolve the UI project root from this script's own location so codegen works
# both standalone and when this repo is vendored inside a monorepo subtree.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPSCHEMA="$(mktemp -t openapi-XXXXXX.json)"
trap 'rm -f "$TMPSCHEMA"' EXIT

cd "$REPO_ROOT"
PYTHONPATH="$REPO_ROOT" python3 scripts/dump_openapi.py > "$TMPSCHEMA"

cd "$REPO_ROOT/frontend"
npx --yes @hey-api/openapi-ts \
    --input "$TMPSCHEMA" \
    --output src/lib/types/api.gen.ts \
    --plugins @hey-api/typescript

# Banner. Generator emits its own header but a project-specific reminder
# helps editors clicking into the file before any manual edit.
TARGET="$REPO_ROOT/frontend/src/lib/types/api.gen.ts"
if [ -f "$TARGET" ]; then
    sed -i '1i // Generated by scripts/codegen.sh - DO NOT EDIT' "$TARGET"
elif [ -f "$REPO_ROOT/frontend/src/lib/types/api.gen.ts/types.gen.ts" ]; then
    # hey-api may emit a directory; rename and banner the inner file.
    mv "$REPO_ROOT/frontend/src/lib/types/api.gen.ts" \
       "$REPO_ROOT/frontend/src/lib/types/api.gen.tmp"
    mv "$REPO_ROOT/frontend/src/lib/types/api.gen.tmp/types.gen.ts" "$TARGET"
    rm -rf "$REPO_ROOT/frontend/src/lib/types/api.gen.tmp"
    sed -i '1i // Generated by scripts/codegen.sh - DO NOT EDIT' "$TARGET"
fi
