name: 🔧 Feature request
description: Suggest an idea for this project
title: "🔧 <title>"
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Is this feature missing in the latest version?
      description: Please upgrade to the latest version to verify that this feature is still missing.
      options:
        - label: I'm using the latest release
          required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: requests
    attributes:
      label: Describe the solution you'd like?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered?
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? or References?

        Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](./CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
