name: 🚩 Security Report
description: Create a report about a potential security issue
title: "🚩 <title>"
labels: [Security]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-is-the-issue
    attributes:
      label: Describe the issue ?
      description: A clear and concise description of what the security issue is
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: correction
    attributes:
      label: If you are aware of a fix please provide it
      description: If you are able please provide the correction here
      placeholder: ....
        
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? or References?

        Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
