ARG BASE_TAG=latest
FROM uprightbass360/arm-transcoder-base:${BASE_TAG}

# AMD VCN/VAAPI via Mesa
RUN apt-get update && apt-get install -y --no-install-recommends \
    mesa-va-drivers \
    && rm -rf /var/lib/apt/lists/*

ENV GPU_VENDOR=amd
