name: "Run ShellCheck"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    shellcheck:
        runs-on: ubuntu-latest
        steps:
            - name: Run ShellCheck
              uses: bewuethr/shellcheck-action@v2.3.0
